/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_web_foldersearch_FolderSearch */

#ifndef _Included_com_web_foldersearch_FolderSearch
#define _Included_com_web_foldersearch_FolderSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_web_foldersearch_FolderSearch
 * Method:    startSearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_web_foldersearch_FolderSearch_startSearch
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
